<?php
declare(strict_types=1);

namespace App\Domain\Mail\ValueObject\MailBounceLogs;

use App\Domain\Shared\ValueObject\Trait\IntTrait;
use DomainException;
use Stringable;

class IsAutoGenerated implements Stringable
{
    use IntTrait;

    private ?int $value;

    /**
     * @param ?string $value
     */
    public function __construct(?string $value)
    {
        if ($value === null || $value === '') {
            $this->value = null;

            return;
        }

        if (!preg_match('/^[01]$/', $value)) {
            throw new DomainException(
                self::class . ' value out of range Error'
                . '[allowed: 0, 1]'
                . '[value: ' . mb_strimwidth($value, 0, 200, '...') . ']',
            );
        }

        $this->value = (int)$value;
    }
}
