<?php
declare(strict_types=1);

namespace App\Test\TestCase\Domain\Mail;

use App\Domain\Mail\Entity\Mail;
use App\Domain\Mail\Entity\MailBounceLog;
use App\Domain\Mail\Entity\MailReceivedCheckLog;
use App\Domain\Mail\Entity\MailSentLog;
use Cake\TestSuite\TestCase;

final class MailDomainSchemaAlignmentTest extends TestCase
{
    public function testMailEntityOriginalMessageIdAccessorReturnsValueObject(): void
    {
        $entity = new Mail(
            id: '1',
            original_message_id: '<m-1@example.com>',
            related_data_key: 'rel-1',
            send_status: 'WAITING',
            send_scheduled_at: '2026-05-11T00:00:00',
            title: 'subject',
            body: 'body',
            mail_to: 'to@example.com',
            mail_cc: null,
            mail_bcc: null,
            mail_received_check: 'received@example.com',
            mail_return_path: 'bounce@example.com',
            created: '2026-05-11T00:00:00',
            created_by: '1',
            created_ip: '127.0.0.1',
            modified: '2026-05-11T00:00:00',
            modified_by: '1',
            modified_ip: '127.0.0.1',
        );

        $this->assertSame('<m-1@example.com>', $entity->originalMessageId()->toStringOrNull());
    }

    public function testMailSentLogSupportsOriginalMessageId(): void
    {
        $entity = new MailSentLog(
            id: '11111111-1111-1111-1111-111111111111',
            mail_id: '1',
            original_message_id: '<m-1@example.com>',
            send_status: 'SENT',
            error_message: null,
            sent_at: '2026-05-11T00:00:00',
            created: '2026-05-11T00:00:00',
            created_by: '1',
            created_ip: '127.0.0.1',
        );

        $this->assertSame('<m-1@example.com>', $entity->originalMessageId()->toStringOrNull());
    }

    public function testMailReceivedCheckLogSupportsNewColumns(): void
    {
        $entity = new MailReceivedCheckLog(
            id: '22222222-2222-2222-2222-222222222222',
            mail_id: '1',
            original_message_id: '<m-2@example.com>',
            checked_address: 'received@example.com',
            checked_at: '2026-05-11T00:00:00',
            created: '2026-05-11T00:00:00',
            created_by: '1',
            created_ip: '127.0.0.1',
        );

        $this->assertSame('<m-2@example.com>', $entity->originalMessageId()->toStringOrNull());
        $this->assertSame('received@example.com', $entity->checkedAddress()->toString());
    }

    public function testMailBounceLogSupportsNewSchemaColumns(): void
    {
        $entity = new MailBounceLog(
            id: '33333333-3333-3333-3333-333333333333',
            mail_id: '1',
            original_message_id: '<m-3@example.com>',
            bounced_email: 'bounce@example.com',
            recipient_type: 'TO',
            action: 'failed',
            status_code: '5.1.1',
            diagnostic_code: 'Mailbox not found',
            bounce_type: 'HARD',
            remote_mta: 'mx.example.com',
            reporting_mta: 'report.example.com',
            arrival_date: '2026-05-11T00:00:00',
            bounced_at: '2026-05-11T00:00:00',
            raw_headers: 'header',
            raw_body: 'body',
            raw_message: 'message',
            parsed_json: '{"k":"v"}',
            provider: 'gmail',
            is_auto_generated: '1',
            created: '2026-05-11T00:00:00',
            created_by: '1',
            created_ip: '127.0.0.1',
        );

        $this->assertSame('bounce@example.com', $entity->bouncedEmail()->toString());
        $this->assertSame('Mailbox not found', $entity->diagnosticCode()->toStringOrNull());
        $this->assertSame('HARD', $entity->bounceType()->toString());
        $this->assertSame('{"k":"v"}', $entity->parsedJson()->toString());
        $this->assertSame(1, $entity->isAutoGenerated()->toIntOrNull());
    }
}
