<?php
declare(strict_types=1);

namespace App\Test\TestCase\Domain\Mail;

use App\Domain\Mail\Entity\Mail;
use App\Domain\Mail\Entity\MailBounceLog;
use App\Domain\Mail\Entity\MailReceivedCheckLog;
use App\Domain\Mail\Entity\MailSentLog;
use Cake\TestSuite\TestCase;
use ReflectionClass;

final class MailDomainSchemaAlignmentTest extends TestCase
{
    public function testMailEntityHasOriginalMessageIdAccessor(): void
    {
        $reflection = new ReflectionClass(Mail::class);
        $this->assertTrue($reflection->hasMethod('originalMessageId'));
    }

    public function testMailSentLogHasNewSchemaAccessors(): void
    {
        $reflection = new ReflectionClass(MailSentLog::class);
        $this->assertTrue($reflection->hasMethod('originalMessageId'));
    }

    public function testMailReceivedCheckLogHasNewSchemaAccessors(): void
    {
        $reflection = new ReflectionClass(MailReceivedCheckLog::class);
        $this->assertTrue($reflection->hasMethod('originalMessageId'));
        $this->assertTrue($reflection->hasMethod('checkedAddress'));
    }

    public function testMailBounceLogHasNewSchemaAccessors(): void
    {
        $reflection = new ReflectionClass(MailBounceLog::class);
        $this->assertTrue($reflection->hasMethod('bouncedEmail'));
        $this->assertTrue($reflection->hasMethod('diagnosticCode'));
        $this->assertTrue($reflection->hasMethod('bounceType'));
        $this->assertTrue($reflection->hasMethod('parsedJson'));
        $this->assertTrue($reflection->hasMethod('isAutoGenerated'));
    }
}
