<?php
declare(strict_types=1);

namespace App\Domain\Mail\Entity;

use App\Domain\Mail\ValueObject\MailBounceLogs as Vo;
use App\Domain\Shared\ValueObject as SVo;

final class MailBounceLog
{
    /**
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\Id $id
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\MailId $mail_id
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\OriginalMessageId $original_message_id
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\BouncedEmail $bounced_email
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\RecipientType $recipient_type
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\Action $action
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\StatusCode $status_code
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\DiagnosticCode $diagnostic_code
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\BounceType $bounce_type
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\RemoteMta $remote_mta
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\ReportingMta $reporting_mta
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\ArrivalDate $arrival_date
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\BouncedAt $bounced_at
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\RawHeaders $raw_headers
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\RawBody $raw_body
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\RawMessage $raw_message
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\ParsedJson $parsed_json
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\Provider $provider
     * @param \App\Domain\Mail\ValueObject\MailBounceLogs\IsAutoGenerated $is_auto_generated
     * @param \App\Domain\Shared\ValueObject\Created $created
     * @param \App\Domain\Shared\ValueObject\CreatedBy $created_by
     * @param \App\Domain\Shared\ValueObject\CreatedIp $created_ip
     */
    public function __construct(
        private readonly Vo\Id $id,
        private readonly Vo\MailId $mail_id,
        private readonly Vo\OriginalMessageId $original_message_id,
        private readonly Vo\BouncedEmail $bounced_email,
        private readonly Vo\RecipientType $recipient_type,
        private readonly Vo\Action $action,
        private readonly Vo\StatusCode $status_code,
        private readonly Vo\DiagnosticCode $diagnostic_code,
        private readonly Vo\BounceType $bounce_type,
        private readonly Vo\RemoteMta $remote_mta,
        private readonly Vo\ReportingMta $reporting_mta,
        private readonly Vo\ArrivalDate $arrival_date,
        private readonly Vo\BouncedAt $bounced_at,
        private readonly Vo\RawHeaders $raw_headers,
        private readonly Vo\RawBody $raw_body,
        private readonly Vo\RawMessage $raw_message,
        private readonly Vo\ParsedJson $parsed_json,
        private readonly Vo\Provider $provider,
        private readonly Vo\IsAutoGenerated $is_auto_generated,
        private readonly SVo\Created $created,
        private readonly SVo\CreatedBy $created_by,
        private readonly SVo\CreatedIp $created_ip,
    ) {
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\Id
     */
    public function id(): Vo\Id
    {
        return $this->id;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\MailId
     */
    public function mailId(): Vo\MailId
    {
        return $this->mail_id;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\OriginalMessageId
     */
    public function originalMessageId(): Vo\OriginalMessageId
    {
        return $this->original_message_id;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\BouncedEmail
     */
    public function bouncedEmail(): Vo\BouncedEmail
    {
        return $this->bounced_email;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\RecipientType
     */
    public function recipientType(): Vo\RecipientType
    {
        return $this->recipient_type;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\Action
     */
    public function action(): Vo\Action
    {
        return $this->action;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\StatusCode
     */
    public function statusCode(): Vo\StatusCode
    {
        return $this->status_code;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\DiagnosticCode
     */
    public function diagnosticCode(): Vo\DiagnosticCode
    {
        return $this->diagnostic_code;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\BounceType
     */
    public function bounceType(): Vo\BounceType
    {
        return $this->bounce_type;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\RemoteMta
     */
    public function remoteMta(): Vo\RemoteMta
    {
        return $this->remote_mta;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\ReportingMta
     */
    public function reportingMta(): Vo\ReportingMta
    {
        return $this->reporting_mta;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\ArrivalDate
     */
    public function arrivalDate(): Vo\ArrivalDate
    {
        return $this->arrival_date;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\BouncedAt
     */
    public function bouncedAt(): Vo\BouncedAt
    {
        return $this->bounced_at;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\RawHeaders
     */
    public function rawHeaders(): Vo\RawHeaders
    {
        return $this->raw_headers;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\RawBody
     */
    public function rawBody(): Vo\RawBody
    {
        return $this->raw_body;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\RawMessage
     */
    public function rawMessage(): Vo\RawMessage
    {
        return $this->raw_message;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\ParsedJson
     */
    public function parsedJson(): Vo\ParsedJson
    {
        return $this->parsed_json;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\Provider
     */
    public function provider(): Vo\Provider
    {
        return $this->provider;
    }

    /**
     * @return \App\Domain\Mail\ValueObject\MailBounceLogs\IsAutoGenerated
     */
    public function isAutoGenerated(): Vo\IsAutoGenerated
    {
        return $this->is_auto_generated;
    }

    /**
     * @return \App\Domain\Shared\ValueObject\Created
     */
    public function created(): SVo\Created
    {
        return $this->created;
    }

    /**
     * @return \App\Domain\Shared\ValueObject\CreatedBy
     */
    public function createdBy(): SVo\CreatedBy
    {
        return $this->created_by;
    }

    /**
     * @return \App\Domain\Shared\ValueObject\CreatedIp
     */
    public function createdIp(): SVo\CreatedIp
    {
        return $this->created_ip;
    }
}
